import {
  addOns,
  brand,
  bookingSuccessLaunchMessage,
  launchRouteHeadline,
} from "@/lib/site";
import { formatFrequency } from "@/lib/pricing";
import { policyWindowLabels, requestTypeLabels } from "@/lib/service-policy";
import { america250Promotion } from "@/lib/promotions";
import type {
  AccountDeletionRequestRow,
  BookingRow,
  ContactMessageRow,
  CustomerRequestRow,
  CareerApplicationRow,
  ProfileRow,
  ReferralRow,
} from "@/types/database";

export type EmailTemplate = {
  subject: string;
  html: string;
  text: string;
};

type EmailAudience = "customer" | "internal";

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function emailButton(href: string, label: string) {
  return `<a href="${escapeHtml(href)}" style="display:inline-block;background:#00ff38;color:#050505;padding:13px 18px;border-radius:10px;font-weight:800;text-decoration:none">${escapeHtml(label)}</a>`;
}

function securityNoticeHtml(action: string) {
  return `
    <p style="background:#f8f4e8;border:1px solid #dedbd0;border-radius:12px;padding:14px">
      We received a request to ${escapeHtml(action)}. If you requested this, no action is needed. If you did not request this, contact Clean Curb Co. immediately and change your password.
    </p>
  `;
}

function securityNoticeText(action: string) {
  return `We received a request to ${action}. If you requested this, no action is needed. If you did not request this, contact Clean Curb Co. immediately and change your password.`;
}

function textFooter(audience: EmailAudience = "customer") {
  if (audience === "internal") {
    return [
      "",
      "--",
      "Internal Clean Curb Co. operations email.",
      `Reply-to inbox: ${brand.email}`,
    ].join("\n");
  }

  return [
    "",
    "--",
    "Need help? Just reply to this email and our team will get it.",
    `Clean Curb Co. | ${brand.tagline}`,
    `${brand.phone} | ${brand.email}`,
    "You're receiving this because you contacted or booked with Clean Curb Co.",
  ].join("\n");
}

function customerText(body: string) {
  return `${body}${textFooter("customer")}`;
}

function internalText(body: string) {
  return `${body}${textFooter("internal")}`;
}

function shell(
  title: string,
  body: string,
  options: { audience?: EmailAudience; preview?: string } = {},
) {
  const audience = options.audience ?? "customer";
  const isInternal = audience === "internal";
  const helpLine = isInternal
    ? "Internal Clean Curb Co. operations email."
    : "Need help? Just reply to this email and our team will get it.";
  const reasonLine = isInternal
    ? "This message was generated by Clean Curb Co. operations tools."
    : "You're receiving this because you contacted or booked with Clean Curb Co.";
  const preview = options.preview ?? title;

  return `
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body style="margin:0;padding:0;background:#f5f4ef;color:#111;font-family:Arial,Helvetica,sans-serif">
        <div style="display:none;max-height:0;overflow:hidden;opacity:0">${escapeHtml(preview)}</div>
        <div style="padding:28px 14px;background:#f5f4ef">
          <div style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid #dedbd0;border-radius:16px;overflow:hidden;box-shadow:0 14px 40px rgba(5,5,5,0.08)">
            <div style="background:#050505;color:#ffffff;padding:24px;border-bottom:5px solid #00ff38">
              <p style="margin:0 0 8px;color:#ffe38a;font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase">${isInternal ? "Internal alert" : "Clean Curb Co."}</p>
              <h1 style="margin:0;font-size:28px;line-height:1.1">Clean Curb Co.</h1>
              <p style="margin:8px 0 0;color:#ffe38a;font-weight:800">${escapeHtml(brand.tagline)}</p>
            </div>
            <div style="padding:26px">
              <h2 style="margin:0 0 18px;font-size:24px;line-height:1.2;color:#111">${escapeHtml(title)}</h2>
              <div style="font-size:16px;line-height:1.6;color:#222">
                ${body}
              </div>
            </div>
            <div style="background:#111;color:#f8f4e8;padding:20px 26px;font-size:13px;line-height:1.6">
              <p style="margin:0 0 8px;font-weight:800;color:#ffffff">Clean Curb Co.</p>
              <p style="margin:0 0 10px;color:#d8d2c3">Locally owned, veteran-owned garbage bin cleaning serving Summerville, Goose Creek, Moncks Corner, and surrounding Charleston-area communities.</p>
              <p style="margin:0 0 10px">
                <a href="${escapeHtml(brand.phoneHref)}" style="color:#00ff38;text-decoration:none">${escapeHtml(brand.phone)}</a>
                <span style="color:#807b70"> | </span>
                <a href="${escapeHtml(brand.emailHref)}" style="color:#00ff38;text-decoration:none">${escapeHtml(brand.email)}</a>
              </p>
              <p style="margin:0 0 8px;color:#ffe38a;font-weight:700">${escapeHtml(helpLine)}</p>
              <p style="margin:0 0 8px;color:#c8c2b7">${escapeHtml(reasonLine)}</p>
              <p style="margin:0;color:#9c968a">${escapeHtml(brand.legalNote)}</p>
            </div>
          </div>
        </div>
      </body>
    </html>
  `;
}

function addOnLabels(addOnIds: string[]) {
  if (!addOnIds.length) return "None";

  return addOnIds
    .map((id) => addOns.find((addOn) => addOn.id === id)?.name ?? id)
    .join(", ");
}

export function bookingSummaryHtml(booking: BookingRow) {
  return `
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Name:</strong> ${escapeHtml(booking.first_name)} ${escapeHtml(booking.last_name)}</li>
      <li><strong>Phone:</strong> ${escapeHtml(booking.phone)}</li>
      <li><strong>Email:</strong> ${escapeHtml(booking.email)}</li>
      <li><strong>Address:</strong> ${escapeHtml(booking.street_address)}, ${escapeHtml(booking.city)}, ${escapeHtml(booking.state)} ${escapeHtml(booking.zip_code)}</li>
      <li><strong>Neighborhood:</strong> ${escapeHtml(booking.neighborhood ?? "Not sure")}</li>
      <li><strong>Bins:</strong> ${booking.bin_count}</li>
      <li><strong>Frequency:</strong> ${escapeHtml(formatFrequency(booking.frequency))}</li>
      <li><strong>Add-ons:</strong> ${escapeHtml(addOnLabels(booking.add_ons))}</li>
      <li><strong>Estimated price:</strong> $${booking.estimated_price}</li>
      <li><strong>Notes:</strong> ${escapeHtml(booking.customer_notes ?? "None")}</li>
    </ul>
  `;
}

export function bookingConfirmationTemplate(
  booking: BookingRow,
  options: { accountSetupUrl?: string | null; paymentSetupUrl?: string | null } = {},
): EmailTemplate {
  const america250Claimed = booking.internal_notes?.includes(
      america250Promotion.code,
    );

    const body = `
      <p>Thanks for booking with Clean Curb Co. We received your request and will confirm your service date and final price by email or text.</p>
      <p><strong>${escapeHtml(launchRouteHeadline)}</strong> ${escapeHtml(bookingSuccessLaunchMessage)}</p>
      ${
        america250Claimed
          ? `<p style="background:#f4fff5;border:1px solid #b6efbd;border-radius:12px;padding:14px"><strong>America 250 Deal:</strong> Your request was submitted during the America 250 promotion window. We will confirm eligibility, final discount, route day, and pricing before charging.</p>`
          : ""
      }
    ${
      options.accountSetupUrl
        ? `<p>${emailButton(options.accountSetupUrl, "Create account")}</p>`
        : ""
    }
    ${
      options.paymentSetupUrl
        ? `<p>${emailButton(options.paymentSetupUrl, "Add payment info")}</p>
           <p>You can securely add payment information now if you'd like. Your payment details are handled securely through Stripe. Clean Curb Co. does not store your full card number or CVC. You will not be charged until your service/payment terms are confirmed.</p>`
        : ""
    }
    ${bookingSummaryHtml(booking)}
    <p>Trash day should not stink all week. We are on it.</p>
  `;

  return {
    subject: "We received your Clean Curb Co. booking request",
    html: shell("Booking request received", body),
    text: customerText(
      [
        `We received your Clean Curb Co. booking request for ${booking.street_address}.`,
        `${launchRouteHeadline} ${bookingSuccessLaunchMessage}`,
        `Estimated price: $${booking.estimated_price}.`,
        options.accountSetupUrl ? `Create account: ${options.accountSetupUrl}` : "",
        options.paymentSetupUrl
          ? `Add payment info securely through Stripe: ${options.paymentSetupUrl}. Clean Curb Co. does not store your full card number or CVC. You will not be charged until service/payment terms are confirmed.`
          : "",
      ]
        .filter(Boolean)
        .join(" "),
    ),
  };
}

export function adminBookingNotificationTemplate(
  booking: BookingRow,
): EmailTemplate {
  return {
    subject: "[Admin] New Clean Curb Co. booking request",
    html: shell("New booking request", bookingSummaryHtml(booking), {
      audience: "internal",
    }),
    text: internalText(
      `New booking: ${booking.first_name} ${booking.last_name}, ${booking.phone}, ${booking.email}, ${booking.street_address}, $${booking.estimated_price}.`,
    ),
  };
}

export function accountSetupTemplate(
  booking: BookingRow,
  setupLink: string,
): EmailTemplate {
  const body = `
    <p>Want to manage everything online? Create your Clean Curb Co. account to view booking status, service updates, payment links, and future before/after photos.</p>
    <p>${emailButton(setupLink, "Set up your account")}</p>
    ${bookingSummaryHtml(booking)}
  `;

  return {
    subject: "Set up your Clean Curb Co. account",
    html: shell("Set up your account", body),
    text: customerText(`Set up your Clean Curb Co. account: ${setupLink}`),
  };
}

export function routeConfirmationTemplate(
  booking: BookingRow,
  routeDay: string,
): EmailTemplate {
  return {
    subject: "Your Clean Curb Co. route day is confirmed",
    html: shell(
      "Route day confirmed",
      `<p>Your route day is confirmed for <strong>${escapeHtml(routeDay)}</strong>.</p>${bookingSummaryHtml(booking)}`,
    ),
    text: customerText(
      `Your Clean Curb Co. route day is confirmed for ${routeDay}.`,
    ),
  };
}

export function reviewRequestTemplate(booking: BookingRow): EmailTemplate {
  return {
    subject: "How did we do?",
    html: shell(
      "How did we do?",
      `<p>Thanks for trusting Clean Curb Co. with your bins. If the fresh start felt good, we would love a quick review.</p>${bookingSummaryHtml(booking)}`,
    ),
    text: customerText(
      "Thanks for trusting Clean Curb Co. with your bins. We would love a quick review.",
    ),
  };
}

function formatEmailDate(value: string) {
  const date = new Date(`${value}T12:00:00`);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

function formatPaymentDeadline(routeDay: string) {
  const date = new Date(`${routeDay}T12:00:00`);

  if (Number.isNaN(date.getTime())) {
    return "at least 24 hours before service";
  }

  date.setDate(date.getDate() - 1);

  return `${new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  }).format(date)} at the latest`;
}

export function paymentLinkTemplate(
  booking: BookingRow,
): EmailTemplate {
  const paymentLink = booking.payment_link ?? "";

  const routeDay = booking.confirmed_route_day
    ? formatEmailDate(booking.confirmed_route_day)
    : "your confirmed service date";

  const paymentDeadline = booking.confirmed_route_day
    ? formatPaymentDeadline(booking.confirmed_route_day)
    : "at least 24 hours before service";

  const body = `
    <p>Hi ${escapeHtml(booking.first_name)},</p>

    <p>
      You're officially on the Clean Curb Co. route for
      <strong>${escapeHtml(routeDay)}</strong>.
    </p>

    <p>
      Just have your bin at the curb or somewhere easy for us to reach,
      and we'll handle the dirty part.
    </p>

    <p>
      Your total is <strong>$${Number(
        booking.estimated_price,
      ).toFixed(2)}</strong>.
      Payment must be completed by
      <strong>${escapeHtml(paymentDeadline)}</strong>.
    </p>

    ${
      paymentLink
        ? `<p>${emailButton(
            paymentLink,
            "Pay securely with Stripe",
          )}</p>`
        : "<p>Your payment link is still being prepared. Please reply to this email so we can fix it.</p>"
    }

    ${bookingSummaryHtml(booking)}

    <p>
      Thanks again for trusting us with the grime. We'll see you at the curb!
    </p>
  `;

  return {
    subject: `Service confirmed for ${routeDay} | Clean Curb Co.`,
    html: shell(
      "Your route is confirmed",
      body,
      {
        preview: `Your Clean Curb Co. service is scheduled for ${routeDay}.`,
      },
    ),
    text: customerText(
      [
        `Hi ${booking.first_name},`,
        `Your Clean Curb Co. service is confirmed for ${routeDay}.`,
        `Please have your bin at the curb or somewhere easily accessible.`,
        `Total: $${Number(
          booking.estimated_price,
        ).toFixed(2)}.`,
        `Payment is due by ${paymentDeadline}.`,
        paymentLink
          ? `Pay securely here: ${paymentLink}`
          : "Your payment link is still being prepared.",
        "Thanks again for trusting us with the grime!",
      ].join("\n\n"),
    ),
  };
}

export function paymentReceivedTemplate(
  booking: BookingRow,
  amount: number,
  options: {
    accountMode: "new" | "existing";
    accountUrl: string;
    loginUrl: string;
  },
): EmailTemplate {
  const amountLabel =
    Number(amount).toFixed(2);

  const accountSection =
    options.accountMode === "existing"
      ? `
        <p>
          Hey ${escapeHtml(
            booking.first_name,
          )}, welcome back!
        </p>

        <p>
          Your existing Clean Curb Co. account is the
          easiest place to view this booking, check route
          updates, manage your service details, and access
          your before-and-after photos once service is
          complete.
        </p>

        <p>
          ${emailButton(
            options.accountUrl,
            "Sign In to My Account",
          )}
        </p>

        <p>
          Nothing else is required right now unless you
          need to update something.
        </p>
      `
      : `
        <p>
          Hey ${escapeHtml(booking.first_name)}!
          Thank you for choosing Clean Curb Co.
        </p>

        <p>
          You do not have a personal Clean Curb Co.
          account yet, and we strongly recommend creating
          one. It is the easiest way to:
        </p>

        <ul style="line-height:1.7;padding-left:18px">
          <li>
            View your confirmed route day and service
            updates
          </li>
          <li>
            Manage recurring service and future bookings
          </li>
          <li>
            Update your contact and service information
          </li>
          <li>
            View payment history and before-and-after
            photos
          </li>
        </ul>

        <p>
          ${emailButton(
            options.accountUrl,
            "Create My Personal Account",
          )}
        </p>

        <p>
          Already created an account?
          <a href="${escapeHtml(
            options.loginUrl,
          )}">Sign in here</a>.
        </p>
      `;

  const body = `
    <p>
      Payment received. Thank you for trusting Clean Curb
      Co. with your bins.
    </p>

    <ul style="line-height:1.7;padding-left:18px">
      <li>
        <strong>Amount paid:</strong>
        $${amountLabel}
      </li>
      <li>
        <strong>Service address:</strong>
        ${escapeHtml(booking.street_address)},
        ${escapeHtml(booking.city)},
        ${escapeHtml(booking.state)}
        ${escapeHtml(booking.zip_code)}
      </li>
      <li>
        <strong>Service:</strong>
        ${escapeHtml(formatFrequency(booking.frequency))}
        | ${booking.bin_count} bin(s)
      </li>
      <li>
        <strong>Add-ons:</strong>
        ${escapeHtml(addOnLabels(booking.add_ons))}
      </li>
    </ul>

    ${accountSection}

    <p>
      <strong>Fresh Starts at the Curb.</strong>
    </p>
  `;

  const subject =
    options.accountMode === "existing"
      ? `Payment received — welcome back, ${booking.first_name}!`
      : "Thanks for choosing Clean Curb Co. — set up your account";

  const accountText =
    options.accountMode === "existing"
      ? [
          `Hey ${booking.first_name}, welcome back!`,
          "Your booking and payment have been received.",
          `Sign in and connect this booking: ${options.accountUrl}`,
        ]
      : [
          `Hey ${booking.first_name}! Thank you for choosing Clean Curb Co.`,
          "Create your personal account to view route updates, manage service, update your information, and access before-and-after photos.",
          `Create your account: ${options.accountUrl}`,
          `Already have one? Sign in: ${options.loginUrl}`,
        ];

  return {
    subject,
    html: shell("Payment received", body),
    text: customerText(
      [
        `Payment received: $${amountLabel}.`,
        `Service address: ${booking.street_address}, ${booking.city}, ${booking.state} ${booking.zip_code}.`,
        ...accountText,
        "Fresh Starts at the Curb.",
      ].join("\n\n"),
    ),
  };
}

export function fieldOnTheWayTemplate(booking: BookingRow): EmailTemplate {
  const body = `
    <p>Hi ${escapeHtml(booking.first_name)},</p>
    <p>We are heading your way for your Clean Curb Co. service.</p>
    <p>Please make sure your bins are empty and accessible.</p>
    <p><strong>Fresh Starts at the Curb.</strong></p>
  `;

  return {
    subject: "We're on the way - Clean Curb Co.",
    html: shell("We're on the way", body),
    text: customerText(
      `Hi ${booking.first_name}, we are heading your way for your Clean Curb Co. service. Please make sure your bins are empty and accessible. Fresh Starts at the Curb.`,
    ),
  };
}

export function serviceCompletedTemplate(
  booking: BookingRow,
  paymentLink?: string | null,
): EmailTemplate {
  const body = `
    <p>Hi ${escapeHtml(booking.first_name)},</p>
    <p>Your Clean Curb Co. service is complete. Thanks for letting us handle the grime at the curb.</p>
    <p>Your before/after photos will be available in your customer portal when your account is connected.</p>
    ${
      paymentLink
        ? `<p>${emailButton(paymentLink, "Pay for this service")}</p>`
        : ""
    }
    <p><strong>Fresh Starts at the Curb.</strong></p>
  `;

  return {
    subject: "Your Clean Curb Co. service is complete",
    html: shell("Service complete", body),
    text: customerText(
      paymentLink
        ? `Your Clean Curb Co. service is complete. Payment link: ${paymentLink}`
        : "Your Clean Curb Co. service is complete. Fresh Starts at the Curb.",
    ),
  };
}

export function customerRequestReceivedTemplate(
  request: CustomerRequestRow,
  booking?: BookingRow | null,
  serviceDate?: string | null,
): EmailTemplate {
  const body = `
    <p>We received your service request. Our team will review it and confirm next steps before making final operational changes.</p>
    ${customerRequestSummaryHtml(request, booking, serviceDate)}
    ${securityNoticeHtml(requestTypeLabels[request.request_type] ?? "change your service")}
    <p>No service is paused, cancelled, or changed until Clean Curb Co. confirms it.</p>
  `;

  return {
    subject: "We received your Clean Curb Co. service request",
    html: shell("Service request received", body),
    text: customerText(
      `We received your Clean Curb Co. service request: ${request.request_type}. Our team will review it and confirm next steps. ${securityNoticeText(requestTypeLabels[request.request_type] ?? "change your service")}`,
    ),
  };
}

export function customerRequestUpdatedTemplate(
  request: CustomerRequestRow,
): EmailTemplate {
  const statusLabel = request.status.replaceAll("_", " ");

  const body = `
    <p>We made a decision on your Clean Curb Co. service request.</p>
    <p><strong>Decision:</strong> ${escapeHtml(statusLabel)}</p>
    ${customerRequestSummaryHtml(request)}
    ${
      request.customer_visible_admin_message
        ? `<p><strong>Message from Clean Curb Co.:</strong> ${escapeHtml(request.customer_visible_admin_message)}</p>`
        : ""
    }
    <p>If you have questions, reply to this email and our team will help.</p>
  `;

  return {
    subject: "Decision on your Clean Curb Co. service request",
    html: shell("Service request decision", body),
    text: customerText(
      `We made a decision on your Clean Curb Co. service request. Decision: ${statusLabel}. ${request.customer_visible_admin_message ?? ""}`.trim(),
    ),
  };
}

export function accountDeletionRequestedTemplate(
  request: AccountDeletionRequestRow,
  profile: ProfileRow,
): EmailTemplate {
  const body = `
    <p>We received your Clean Curb Co. account deletion request. Our team will review it before processing because account records can include bookings, service history, checklist PDFs, payment references, and legal or operational records.</p>
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Status:</strong> ${escapeHtml(request.status)}</li>
      <li><strong>Submitted:</strong> ${escapeHtml(new Date(request.created_at).toLocaleString("en-US"))}</li>
      <li><strong>Account:</strong> ${escapeHtml(profile.email ?? request.customer_email ?? "Customer account")}</li>
    </ul>
    ${securityNoticeHtml("delete your Clean Curb Co. account")}
  `;

  return {
    subject: "We received your Clean Curb Co. account deletion request",
    html: shell("Account deletion request received", body),
    text: customerText(
      `We received your Clean Curb Co. account deletion request. Our team will review it before processing. ${securityNoticeText("delete your Clean Curb Co. account")}`,
    ),
  };
}

export function adminAccountDeletionRequestTemplate(
  request: AccountDeletionRequestRow,
  profile: ProfileRow,
  adminUrl: string,
): EmailTemplate {
  const body = `
    <p>A customer requested account deletion. Review before disabling portal access or processing deletion.</p>
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Customer:</strong> ${escapeHtml([profile.first_name, profile.last_name].filter(Boolean).join(" ") || profile.email || "Customer")}</li>
      <li><strong>Email:</strong> ${escapeHtml(profile.email ?? request.customer_email ?? "No email")}</li>
      <li><strong>Reason:</strong> ${escapeHtml(request.request_reason ?? "No reason provided")}</li>
      <li><strong>Status:</strong> ${escapeHtml(request.status)}</li>
    </ul>
    <p>${emailButton(adminUrl, "Open request queue")}</p>
  `;

  return {
    subject: "[Admin] Account deletion request - Clean Curb Co.",
    html: shell("Account deletion request", body, { audience: "internal" }),
    text: internalText(
      `Account deletion request from ${profile.email ?? request.customer_email ?? "customer"}. Admin: ${adminUrl}`,
    ),
  };
}

export function accountDeletionDecisionTemplate(
  request: AccountDeletionRequestRow,
  statusLabel: string,
): EmailTemplate {
  const body = `
    <p>Your Clean Curb Co. account deletion request was updated.</p>
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Status:</strong> ${escapeHtml(statusLabel)}</li>
      <li><strong>Message:</strong> ${escapeHtml(request.customer_visible_admin_message ?? "Please contact us if you have questions.")}</li>
    </ul>
    <p>If you have questions about retained service, payment, or legal records, reply to this email and our team will help.</p>
  `;

  return {
    subject: "Update on your Clean Curb Co. account deletion request",
    html: shell("Account request updated", body),
    text: customerText(
      `Your account deletion request status is now ${statusLabel}. ${request.customer_visible_admin_message ?? "Please contact us if you have questions."}`,
    ),
  };
}

export function bookingDecisionTemplate(
  booking: BookingRow,
  decision: "accepted" | "declined" | "needs_more_information",
  message?: string | null,
): EmailTemplate {
  const titles = {
    accepted: "Booking accepted",
    declined: "Booking declined",
    needs_more_information: "We need a little more information",
  };
  const body = `
    <p>${escapeHtml(decisionCopy(decision))}</p>
    ${message ? `<p><strong>Message from Clean Curb Co.:</strong> ${escapeHtml(message)}</p>` : ""}
    ${bookingSummaryHtml(booking)}
  `;

  return {
    subject: `${titles[decision]} - Clean Curb Co.`,
    html: shell(titles[decision], body),
    text: customerText(
      `${decisionCopy(decision)} ${message ?? ""}`.trim(),
    ),
  };
}

export function routeDateOfferedTemplate(
  booking: BookingRow,
  portalUrl: string,
): EmailTemplate {
  const routeDay = booking.proposed_route_day ?? booking.confirmed_route_day ?? "";
  const body = `
    <p>We can service your address on <strong>${escapeHtml(routeDay)}</strong>. Please confirm or decline the proposed route day in your customer portal.</p>
    ${booking.route_offer_message ? `<p>${escapeHtml(booking.route_offer_message)}</p>` : ""}
    <p>${emailButton(portalUrl, "Review route date")}</p>
    ${bookingSummaryHtml(booking)}
  `;

  return {
    subject: "Please confirm your Clean Curb Co. route date",
    html: shell("Route date offered", body),
    text: customerText(
      `We can service your address on ${routeDay}. Please confirm or decline in your portal: ${portalUrl}`,
    ),
  };
}

export function routeDateResponseTemplate(
  booking: BookingRow,
  response: "confirmed" | "declined",
): EmailTemplate {
  const body = `
    <p>We received your route date ${escapeHtml(response)} response.</p>
    <p>${
      response === "confirmed"
        ? `Your route date is confirmed for ${escapeHtml(booking.confirmed_route_day ?? booking.proposed_route_day ?? "the proposed date")}.`
        : "Our team will follow up with another route option."
    }</p>
    ${securityNoticeHtml(`${response} a route date`)}
  `;

  return {
    subject:
      response === "confirmed"
        ? "Your Clean Curb Co. route date is confirmed"
        : "We received your route date response",
    html: shell(
      response === "confirmed" ? "Route date confirmed" : "Route date declined",
      body,
    ),
    text: customerText(
      response === "confirmed"
        ? `Your Clean Curb Co. route date is confirmed for ${booking.confirmed_route_day ?? booking.proposed_route_day ?? "the proposed date"}. ${securityNoticeText("confirm a route date")}`
        : `We received your declined route date response. Our team will follow up with another option. ${securityNoticeText("decline a route date")}`,
    ),
  };
}

export function adminRouteDateResponseTemplate(
  booking: BookingRow,
  response: "confirmed" | "declined",
): EmailTemplate {
  return {
    subject: `[Admin] Customer ${response} route date - Clean Curb Co.`,
    html: shell(
      `Customer ${response} route date`,
      `<p>${escapeHtml(booking.first_name)} ${escapeHtml(booking.last_name)} ${escapeHtml(response)} the route date for ${escapeHtml(booking.street_address)}.</p>${bookingSummaryHtml(booking)}`,
      { audience: "internal" },
    ),
    text: internalText(
      `Customer ${response} route date for booking ${booking.id}, ${booking.street_address}.`,
    ),
  };
}

export function paymentSetupInviteTemplate(
  booking: BookingRow,
  setupUrl: string,
  accountSetupUrl?: string | null,
): EmailTemplate {
  const body = `
    <p>You can securely add payment information now if you'd like, so your account is ready when your route is confirmed.</p>
    <p>${emailButton(setupUrl, "Add payment info")}</p>
    ${accountSetupUrl ? `<p>${emailButton(accountSetupUrl, "Create account")}</p>` : ""}
    <p>Your payment details are handled securely through Stripe. Clean Curb Co. does not store your full card number or CVC. You will not be charged until your service/payment terms are confirmed.</p>
    ${bookingSummaryHtml(booking)}
  `;

  return {
    subject: "Optional payment setup for your Clean Curb Co. booking",
    html: shell("Add payment info when ready", body),
    text: customerText(
      `You can securely add payment information now if you'd like: ${setupUrl}. Clean Curb Co. does not store your full card number or CVC. You will not be charged until service/payment terms are confirmed.`,
    ),
  };
}

export function paymentSetupCompletedTemplate(booking: BookingRow): EmailTemplate {
  return {
    subject: "Payment information added - Clean Curb Co.",
    html: shell(
      "Payment information added",
      `<p>Your payment information was added successfully through Stripe. Clean Curb Co. does not store your full card number or CVC.</p>${bookingSummaryHtml(booking)}`,
    ),
    text: customerText(
      "Your payment information was added successfully through Stripe. Clean Curb Co. does not store your full card number or CVC.",
    ),
  };
}

function decisionCopy(decision: "accepted" | "declined" | "needs_more_information") {
  if (decision === "accepted") {
    return "Your Clean Curb Co. booking request has been accepted. We will keep you posted as your route is scheduled.";
  }
  if (decision === "declined") {
    return "We are sorry, but we cannot accept that booking request as submitted. Please contact us if you would like to discuss another option.";
  }
  return "Our team needs a little more information before we can finalize your Clean Curb Co. booking request.";
}

export function adminCustomerRequestAlertTemplate(
  request: CustomerRequestRow,
  profile: ProfileRow,
  booking?: BookingRow | null,
  serviceDate?: string | null,
): EmailTemplate {
  const body = `
    <p>A customer submitted a service change request.</p>
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Customer:</strong> ${escapeHtml([profile.first_name, profile.last_name].filter(Boolean).join(" ") || profile.email || "Customer")}</li>
      <li><strong>Email:</strong> ${escapeHtml(profile.email ?? booking?.email ?? "No email")}</li>
      <li><strong>Phone:</strong> ${escapeHtml(profile.phone ?? booking?.phone ?? "No phone")}</li>
      <li><strong>Booking:</strong> ${escapeHtml(booking?.id ?? request.booking_id ?? "No booking")}</li>
      <li><strong>Scheduled date:</strong> ${escapeHtml(serviceDate ?? "No scheduled date")}</li>
    </ul>
    ${customerRequestSummaryHtml(request, booking, serviceDate, {
      includeAdminNotes: true,
    })}
  `;

  return {
    subject: "[Admin] Customer service change request - Clean Curb Co.",
    html: shell("Customer service change request", body, {
      audience: "internal",
    }),
    text: internalText(
      `Customer service change request: ${request.request_type}, ${request.policy_window}.`,
    ),
  };
}

function customerRequestSummaryHtml(
  request: CustomerRequestRow,
  booking?: BookingRow | null,
  serviceDate?: string | null,
  options: { includeAdminNotes?: boolean } = {},
) {
  const adminNote = options.includeAdminNotes
    ? `<li><strong>Admin note:</strong> ${escapeHtml(request.admin_notes ?? "No note added")}</li>`
    : "";

  return `
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Request:</strong> ${escapeHtml(requestTypeLabels[request.request_type] ?? request.request_type.replaceAll("_", " "))}</li>
      <li><strong>Status:</strong> ${escapeHtml(request.status.replaceAll("_", " "))}</li>
      <li><strong>Scheduled date:</strong> ${escapeHtml(serviceDate ?? booking?.confirmed_route_day ?? booking?.requested_date ?? "Not scheduled")}</li>
      <li><strong>Policy window:</strong> ${escapeHtml(policyWindowLabels[request.policy_window] ?? request.policy_window)}</li>
      <li><strong>Acknowledgment:</strong> ${request.policy_acknowledged ? `Completed by ${escapeHtml(request.policy_acknowledged_name ?? "customer")}` : "Not required or not completed"}</li>
      <li><strong>Original estimated price:</strong> ${request.original_estimated_price === null ? "Not recorded" : `$${request.original_estimated_price}`}</li>
      <li><strong>Cancellation fee:</strong> ${request.cancellation_fee === null ? "None configured" : `$${request.cancellation_fee}`}</li>
      <li><strong>Full charge may apply:</strong> ${request.full_charge_applies ? "Yes" : "No"}</li>
      <li><strong>Message:</strong> ${escapeHtml(request.message ?? "None provided")}</li>
      ${adminNote}
    </ul>
  `;
}

export function referralRewardTemplate(
  referral: ReferralRow,
  mode: "ready" | "sent",
): EmailTemplate {
  const rewardValue = referral.reward_value ?? 5;
  const body = `
    <p>Your neighbor referral is ${mode === "ready" ? "ready for reward review" : "marked as rewarded"}.</p>
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Referral code:</strong> ${escapeHtml(referral.referral_code ?? "Not provided")}</li>
      <li><strong>Status:</strong> ${escapeHtml(referral.status.replaceAll("_", " "))}</li>
      <li><strong>Reward:</strong> $${rewardValue} service credit</li>
    </ul>
  `;

  return {
    subject:
      mode === "ready"
        ? "Your Clean Curb Co. referral reward is ready"
        : "Your Clean Curb Co. referral reward was sent",
    html: shell(
      mode === "ready" ? "Referral reward ready" : "Referral reward sent",
      body,
    ),
    text: customerText(`Your Clean Curb Co. referral reward is ${mode}.`),
  };
}

export function contactConfirmationTemplate(
  message: ContactMessageRow,
): EmailTemplate {
  return {
    subject: "We received your message - Clean Curb Co.",
    html: shell(
      "Message received",
      `<p>Thanks, ${escapeHtml(message.name)}. We received your message and will follow up soon.</p><p><strong>Reason:</strong> ${escapeHtml(message.reason)}</p><p>${escapeHtml(message.message)}</p>`,
    ),
    text: customerText(
      `Thanks, ${message.name}. We received your Clean Curb Co. message and will follow up soon.`,
    ),
  };
}

export function adminContactNotificationTemplate(
  message: ContactMessageRow,
): EmailTemplate {
  return {
    subject: "[Admin] New Clean Curb Co. contact message",
    html: shell(
      "New contact message",
      `<ul style="line-height:1.7;padding-left:18px">
        <li><strong>Name:</strong> ${escapeHtml(message.name)}</li>
        <li><strong>Phone:</strong> ${escapeHtml(message.phone ?? "Not provided")}</li>
        <li><strong>Email:</strong> ${escapeHtml(message.email)}</li>
        <li><strong>Area:</strong> ${escapeHtml(message.address_or_neighborhood ?? "Not provided")}</li>
        <li><strong>Reason:</strong> ${escapeHtml(message.reason)}</li>
      </ul>
      <p>${escapeHtml(message.message)}</p>`,
      { audience: "internal" },
    ),
    text: internalText(
      `New contact message from ${message.name}: ${message.reason}. ${message.message}`,
    ),
  };
}

export function careerApplicationConfirmationTemplate(
  application: CareerApplicationRow,
): EmailTemplate {
  const body = `
    <p>Hi ${escapeHtml(application.first_name)},</p>
    <p>Thanks for your interest in Clean Curb Co.</p>
    <p>We received your information and will keep it on file as we grow our local route team.</p>
    <p><strong>Fresh Starts at the Curb,</strong><br />Clean Curb Co.</p>
  `;

  return {
    subject: "We received your Clean Curb Co. career interest form",
    html: shell("Career interest received", body),
    text: customerText(
      `Hi ${application.first_name}, thanks for your interest in Clean Curb Co. We received your information and will keep it on file as we grow our local route team. Fresh Starts at the Curb, Clean Curb Co.`,
    ),
  };
}

export function adminCareerApplicationTemplate(
  application: CareerApplicationRow,
  adminUrl: string,
): EmailTemplate {
  const body = `
    <p>A new Clean Curb Co. career interest form was submitted.</p>
    <ul style="line-height:1.7;padding-left:18px">
      <li><strong>Name:</strong> ${escapeHtml(application.first_name)} ${escapeHtml(application.last_name)}</li>
      <li><strong>Email:</strong> ${escapeHtml(application.email)}</li>
      <li><strong>Phone:</strong> ${escapeHtml(application.phone ?? "Not provided")}</li>
      <li><strong>Role interest:</strong> ${escapeHtml(application.role_interest ?? "General Interest")}</li>
      <li><strong>Availability:</strong> ${escapeHtml(application.availability.join(", ") || "Not provided")}</li>
      <li><strong>Location:</strong> ${escapeHtml([application.city, application.state, application.zip].filter(Boolean).join(", ") || "Not provided")}</li>
    </ul>
    <p><strong>Experience:</strong><br />${escapeHtml(application.experience ?? "Not provided")}</p>
    <p><strong>Message:</strong><br />${escapeHtml(application.message ?? "Not provided")}</p>
    <p>${emailButton(adminUrl, "Open admin careers")}</p>
  `;

  return {
    subject: "[Admin] New Clean Curb Co. career application",
    html: shell("New career application", body, { audience: "internal" }),
    text: internalText(
      `New career application: ${application.first_name} ${application.last_name}, ${application.email}, ${application.role_interest ?? "General Interest"}. Admin: ${adminUrl}`,
    ),
  };
}
